#!/bin/bash

# test: Test debops.postgresql_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ferm debops.apt_preferences debops.etc_services


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}
sudo rm -rf /var/lib/postgresql


echo "Debugging PG..."

echo "Disable no_log: True"
sed -i 's/no_log: True/no_log: False/' /home/travis/build/debops/ansible-postgresql_server/tasks/secure_installation.yml

echo "Show list of running PG processes"
ps aux | grep postg

echo "Show list of PG instances"
ls -l /var/lib/postgresql

echo "Show list of Ansible facts"
ansible all -m setup -b

assert_playbook_check_runs
assert_playbook_idempotent


assert_running "postgres"
assert_docs
