#!/bin/bash

# test: Test debops.postgresql_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ferm debops.apt_preferences debops.etc_services


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}
sudo rm -rf /var/lib/postgresql


assert_playbook_check_runs
assert_playbook_idempotent


assert_running "postgres"
assert_docs
