#!/bin/bash

# test: Test debops.logrotate
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/logrotate.d/custom"
assert_in_file "/etc/logrotate.d/custom" "missingok"
assert_docs

