#!/bin/bash

# test: Test debops.ntp
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


role_dependencies debops.ferm


echo "Timezone before the playbook"
cat /etc/timezone


assert_playbook_runs


echo "Timezone after the playbook"
cat /etc/timezone


assert_playbook_idempotent


# Check if correct timezone is set
assert_in_file "/etc/timezone" "America/New_York"

# Check if ntpd is not installed on OpenVZ containers
assert_path "/usr/sbin/ntpd" !
assert_path "/usr/sbin/openntpd" !

