#!/bin/bash

# test: Test debops.apt
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


assert_playbook_runs
assert_playbook_idempotent

# Check if vim is installed by Ansible
assert_in "$(vim --version)" "VIM"

# Check if webserver for Debian preseed is set up correctly on the local host
assert_url "http://$fqdn"

# Check if apt-cacher-ng is installed and running
assert_path "/usr/sbin/apt-cacher-ng"
assert_running "apt-cacher-ng"
