#!/bin/bash

# test: Test debops.monit
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


sleep 20

assert_monitoring "ssh"

assert_in_file "/etc/monit/conf.d/base_ssh.conf" "timeout 20 seconds"
assert_in_file "/etc/monit/conf.d/base_ssh.conf" "cpu"


assert_playbook_runs --extra-vars '{"monit_process_list":[{"pid":"sshd.pid","process":"ssh","delete":"true"}]}'

sleep 20

assert_monitoring "ssh" !
