#!/bin/bash

# test: Test debops.ferm
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}


assert_playbook_runs
assert_playbook_idempotent


assert_iptables_allow "http"
assert_in "ip6tables -L" "http"
assert_in_file "/etc/ferm/filter-input.d/50_http.conf" "protocol"
