#!/bin/bash

# test: Test debops.ferm
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
cat /etc/ansible/facts.d/ferm.fact
assert_playbook_idempotent


assert_iptables_allow "http"
assert_in_file "/etc/ferm/filter-input.d/50_http.conf" "protocol"
