#!/bin/bash

# test: Test debops.subnetwork
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ifupdown
ansible-galaxy -f install debops.ferm


assert_playbook_check_runs

echo "Show firewall rules"
sudo ls -l /etc/ferm/ferm.d
sudo cp /etc/ferm/ferm.d/50_accept_filter_forward.conf /tmp/forward-old.conf
sudo cat /etc/ferm/ferm.d/50_accept_filter_forward.conf

assert_playbook_check_runs

echo "Show firewall rules"
sudo ls -l /etc/ferm/ferm.d
sudo cp /etc/ferm/ferm.d/50_accept_filter_forward.conf /tmp/forward-new.conf
sudo cat /etc/ferm/ferm.d/50_accept_filter_forward.conf

ls -l /tmp/forward*

diff -s /tmp/forward-old.conf /tmp/forward-new.conf

# FIXME: Disabled for now: https://github.com/debops/ansible-subnetwork/pull/16
# assert_playbook_idempotent


assert_path /etc/network/interfaces

assert_docs
