#!/bin/bash

# test: Test debops.subnetwork
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ifupdown
ansible-galaxy -f install debops.ferm


assert_playbook_check_runs
assert_playbook_idempotent


assert_path /etc/network/interfaces

assert_docs

