#!/bin/bash

# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.apt_preferences
ansible-galaxy -f install debops.ferm
ansible-galaxy -f install debops.nginx

sudo pip3 install virtualenv

assert_playbook_check_runs
assert_playbook_idempotent

# I could not get this to run on Travis.
# Ubuntu trusty is not supported by this role anyway.

# sudo -u homeassistant sh -c 'cd; ~/prod_venv/bin/hass --daemon'
# Give homeassistant time to start.
# sleep 10

# assert_url "http://localhost.localdomain"
# assert_url "http://localhost.localdomain/states"
# assert_url "http://localhost.localdomain/api/"
# curl -k -v "http://localhost.localdomain/api/"

assert_docs
