#!/bin/bash

# test: Test debops.dovecot
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/dovecot/local.conf"
assert_in_file "/etc/dovecot/local.conf" "mail_location"
assert_running "dovecot"

