#!/bin/bash

# test: Test debops.dovecot
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki


sudo apt-get -y install tree


assert_playbook_check_runs

sudo tree /etc/dovecot

assert_playbook_idempotent

assert_path "/etc/dovecot/local.conf"
assert_running "dovecot"

assert_tcp "localhost" "143"
assert_iptables_allow imap

assert_tcp "localhost" "993"
assert_iptables_allow imaps

# Test documentation
assert_docs

