#!/bin/bash

# test: Test debops.ifupdown
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_shellcheck

install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ferm


assert_playbook_check_runs
assert_playbook_idempotent


echo "Network interfaces"
ip addr

echo "Files in the /etc/network/interfaces.d/ directory"
ls -l /etc/network/interfaces.d/
cat /etc/network/interfaces.d/*

if sudo shellcheck ${TRAVIS_BUILD_DIR}/files/script/ifupdown-reconfigure-interfaces ; then
    pass "shellcheck reported no issues."
else
    fail "shellcheck reported issues."
fi

assert_path "/etc/network/interfaces"

assert_docs
