#!/bin/bash

# test: Test debops.ifupdown
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# Well. Currently on GCE, network interfaces don't want to restart, not sure
# yet why. So let's cheat and make them not do anything drastic.
echo "This is static because GCE isn't playing nice" | sudo tee -a /etc/network/interfaces


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/network/interfaces"

assert_docs

