#!/bin/bash

# test: Test debops.mysql
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install debops.mariadb_server


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}


assert_playbook_runs
assert_playbook_idempotent


cat ~/.my.cnf


assert_in "mysql -sN -e 'show databases;'" "testapp"
assert_in "mysql -sN -e 'select * from mysql.user;'" "testapp"

assert_docs

