#!/bin/bash

# test: Test debops.fail2ban
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/fail2ban/jail.local"
assert_running "fail2ban-server"
assert_in_file "/etc/fail2ban/jail.local" "banaction"
assert_exit_code "sudo fail2ban-client -vv status ssh" "0"
assert_docs

