#!/bin/bash

# test: Test debops.redis
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


stop redis-server
purge redis-server
sudo rm -rf /etc/redis
fix_precise_issues


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(sudo redis-cli PING)" "PONG"
#assert_in "$(sudo redis-cli -p 26379 PING)" "PONG"

assert_iptables_allow "redis-server"
#assert_iptables_allow "redis-sentinel"
