#!/bin/bash

# test: Test debops.redis
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


stop redis-server
purge redis-server
sudo rm -rf /etc/redis
fix_precise_issues

install_shellcheck

install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.etc_services debops.ferm


assert_playbook_check_runs
assert_playbook_idempotent


echo "Randomized Redis password: '$(sudo redis-password)'"

echo "Redis information:"
sudo redis-cli -a "$(sudo redis-password)" info


assert_in "$(sudo redis-cli -a $(sudo redis-password) PING)" "PONG"
#assert_in "$(sudo redis-cli -a $(redis-password) -p 26379 PING)" "PONG"

assert_iptables_allow "redis-server"
#assert_iptables_allow "redis-sentinel"

sudo shellcheck /etc/redis/ansible-redis-dynamic.conf || fail "shellcheck reported issues."
shellcheck /tmp/ansible-redis-dynamic.conf || exit 1

assert_docs
