#!/bin/bash

# test: Test debops.ruby
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


if [[ "$is_travis" ]]; then
  __rvm unload ; rm -rf ~/.rvm
fi


role_dependencies debops.backporter


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(ruby -v)" "ruby"
