#!/bin/bash

# test: Test debops.ruby
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


if [[ -n "${ROLESPEC_TRAVIS}" ]]; then
  __rvm unload ; rm -rf ~/.rvm
fi


echo "Clean up the environment"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
unset rvm_bin_path GEM_HOME IRBRC MY_RUBY_HOME rvm_autoupdate_flag rvm_path RACK_ENV rvm_prefix rvm_version RAILS_ENV GEM_PATH RUBY_VERSION rvm_silence_path_mismatch_check_flag

# Add Ruby 2.1 PPA
sudo apt-get -yq install python-software-properties
sudo apt-add-repository -y ppa:brightbox/ruby-ng


assert_playbook_check_runs
assert_playbook_idempotent


assert_in "$(ruby -v)" "ruby"
