#!/bin/bash

# test: Test debops.iscsi
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# We cannot really test open-iscsi in an OpenVZ container, so just try to
# suppress the service from starting up
# Prevent service startup while we are working in chroot
cat <<EOF | sudo tee /usr/sbin/policy-rc.d
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF
sudo chmod +x /usr/sbin/policy-rc.d


# Nuke the cap12s local fact to try and fool the role so that it thinks that
# open-iscsi cannot be run on this host
sudo rm -rf /etc/ansible/facts.d/cap12s.fact


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/lvm/lvm.conf"
assert_path "/etc/iscsi/iscsid.conf"
assert_docs

