#!/bin/bash

# test: Test debops.nodejs
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


purge nodejs


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(nodejs -v)" "v"
