#!/bin/bash

# test: Test debops.nodejs
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}


purge nodejs
upgrade_packages nodejs nodejs-legacy


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(node -v)" "v"
