#!/bin/bash

# test: Test debops.dnsmasq
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Prevent service startup while we are working in chroot
cat <<EOF | sudo tee /usr/sbin/policy-rc.d
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF
sudo chmod +x /usr/sbin/policy-rc.d


upgrade_packages python-jinja2 dnsmasq


sudo rm -rf /usr/sbin/policy-rc.d


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.ferm

assert_playbook_check_runs
assert_playbook_idempotent


# Check if configuration file is present
assert_path "/etc/dnsmasq.d/00_main.conf"

assert_docs
