#!/bin/bash

# test: Test debops.dhparam
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/pki/dhparam"
assert_path "/etc/pki/dhparam/set0"
assert_in_file "/etc/pki/dhparam/set0" "BEGIN DH PARAMETERS"


echo "Show the initial DH parameters"
cat /etc/pki/dhparam/set0

echo
echo "Test DH parameter regeneration ..."
sudo /usr/local/lib/dhparam-generate-params run

echo
echo "Show new DH parameters"
cat /etc/pki/dhparam/set0

assert_in_file "/etc/pki/dhparam/set0" "BEGIN DH PARAMETERS"
assert_docs

