#!/bin/bash

# test: Test debops.users
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"

role_dependencies debops.auth

ssh-keygen -t rsa -P "" -f /tmp/id_rsa


assert_playbook_runs
assert_playbook_idempotent


assert_path "/tmp/testuser"
assert_path "/tmp/testuser/.dotfiles"

assert_user_in_group "testuser" "audio"

assert_in "$(getent passwd | grep testuser)" "sh"
