#!/bin/bash

# test: Test debops.users
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ssh-keygen -t rsa -P "" -f /tmp/id_rsa


assert_playbook_runs
assert_playbook_idempotent


assert_path "/tmp/testuser"
assert_path "/tmp/testuser/.config/dotfiles"

assert_user_in_group "testuser" "audio"

assert_in "$(getent passwd | grep testuser)" "sh"
