#!/bin/bash

# test: Test debops.php
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.logrotate


echo "Check php packages"
dpkg -l | grep php

echo "Check diversions"
dpkg-divert --list

echo "Check php preference"
apt-cache policy php5 php5-fpm

assert_playbook_check_runs

echo "Check diversions"
dpkg-divert --list

echo "Check logrotate config"
ls -l /etc/logrotate.d

echo "Check logrotate contents"
cat /etc/logrotate.d/php*


assert_playbook_idempotent


assert_in "$(php -v)" "PHP"

