#!/bin/bash

# test: Test debops.librenms
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.mariadb_server debops.snmpd


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}


assert_playbook_check_runs
assert_playbook_idempotent


assert_url "http://${ROLESPEC_FQDN}/"

assert_docs

