#!/bin/bash

# test: Test debops.dhcpd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


sudo tail /var/log/syslog


assert_path "/etc/dhcp/dhcpd.conf"
assert_in_file "/etc/dhcp/dhcpd.conf" "subnet"

