#!/bin/bash

# test: Test debops.nginx
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki


node "${ROLESPEC_TEST}/test_files/server" &
sleep 3
chmod 777 /tmp/nodeserver.sock


assert_playbook_check_runs -e "nginx_flavor=${TEST_NGINX_FLAVOR:-full}"
assert_playbook_idempotent -e "nginx_flavor=${TEST_NGINX_FLAVOR:-full}"

echo DEBUG
netstat -nlp
ls -l /etc/nginx/sites-enabled
cat /etc/nginx/sites-enabled/*
tail -n 50 /var/log/nginx/*.log /var/log/syslog

assert_url "http://${ROLESPEC_FQDN}:8080" 301
assert_url "https://${ROLESPEC_FQDN}/"


kill -9 "$(pidof node)"
