#!/bin/bash

# test: Test debops.nginx
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


ansible-galaxy install -f debops.pki


node "${ROLESPEC_TEST}/test_files/server" &
sleep 3
chmod 777 /tmp/nodeserver.sock


assert_playbook_runs
assert_playbook_idempotent


assert_url "http://${ROLESPEC_FQDN}:8080" 307
assert_url "https://${ROLESPEC_FQDN}"


kill -9 "$(pidof node)"
