#!/bin/bash

# test: Test debops.reprepro
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Use reprepro from Trusty, Precise is too old
upgrade_packages reprepro


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/var/lib/reprepro"

# Test documentation
#assert_docs

