#!/bin/bash

# test: Test debops.docker_gen
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Make sure newer start-stop-daemon is present
upgrade_packages dpkg


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.docker


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/default/docker-gen"
assert_path "/etc/docker-gen.conf"
assert_docs

