#!/bin/bash

# test: Test debops.sshkeys
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/ssh/authorized_keys/${USER}"
