#!/bin/bash

# test: Test debops.slapd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible stable-2.0
ansible_plugins


ansible-galaxy install -f debops.pki debops.auth


assert_playbook_check_runs
assert_playbook_idempotent


assert_group openldap
assert_running "slapd"
assert_in_file "/etc/ldap/ldap.conf" "TLS_CACERT"
assert_in "$(ldapsearch -x)" "LDAPv3"
assert_tcp "localhost" "389"
