#!/bin/bash

# test: Test debops.netbox
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


upgrade_packages gunicorn


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences \
                          debops.etc_services \
                          debops.ferm \
                          debops.pki \
                          debops.secret \
                          debops.gunicorn \
                          debops.postgresql \
                          debops.postgresql_server \
                          debops.nginx


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}
sudo rm -rf /var/lib/postgresql


assert_playbook_check_runs
assert_playbook_idempotent


curl http://localhost.localdomain/login/


assert_url "http://localhost.localdomain/login/" 301

# Test documentation
assert_docs
