#!/bin/bash

# test: Test debops.dokuwiki
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.ferm debops.php debops.logrotate debops.nginx


assert_playbook_check_runs
assert_playbook_idempotent


assert_url "http://localhost.localdomain/install.php"

# Test documentation
assert_docs

