#!/bin/bash

# test: Test debops.auth
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


assert_playbook_runs
assert_playbook_idempotent


# Check if all system groups are created
assert_group admins sshusers sftponly webadmins

# Check if user is in admins group
assert_user_in_group $USER admins

# Check if sudoers configuration for admins has correct permissions
assert_permission "/etc/sudoers.d/admins" "440"

# Check if admins group can use sudo without password
assert_in_file "/etc/sudoers.d/admins" "NOPASSWD"
