#!/bin/bash

# test: Test debops.auth
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


# Check if all system groups are created
assert_group admins sshusers sftponly webadmins

# Check if sudoers configuration for admins has correct permissions
assert_permission "/etc/sudoers.d/admins" "440"

# Check if admins group can use sudo without password
assert_in_file "/etc/sudoers.d/admins" "NOPASSWD"
