#!/bin/bash

# test: Test debops.owncloud
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt
ansible-galaxy -f install debops.apt_preferences
ansible-galaxy -f install debops.ferm
ansible-galaxy -f install debops.mariadb_server
ansible-galaxy -f install debops.mariadb
ansible-galaxy -f install debops.php5
ansible-galaxy -f install debops.nginx


assert_playbook_check_runs
assert_playbook_idempotent


echo "curl http://localhost.localdomain/"
curl http://localhost.localdomain


assert_path "/var/www/owncloud"
assert_url "http://localhost.localdomain/"

/usr/local/bin/occ check
/usr/local/bin/occ integrity:check-core
/usr/local/bin/occ user:report
/usr/local/bin/occ status

assert_docs

