#!/bin/bash

# test: Test debops-playbooks common playbook
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -r /home/travis/build/debops/debops-playbooks/galaxy/requirements.txt


hostname --fqdn
pwd


ansible-playbook /home/travis/build/debops/debops-playbooks/playbooks/site.yml


#assert_playbook_runs
#assert_playbook_idempotent

