#!/bin/bash

# test: Test debops-playbooks common playbook
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


debops_roles=$(cat /home/travis/build/debops/debops-playbooks/galaxy/requirements.txt | sed -e 's/^debops\./ansible-/' -e 's/ansible\-ansible/ansible-role-ansible/')


for role in ${debops_roles} ; do
	slug=$(echo ${role} | sed -e 's/^ansible\-role\-//' -e 's/^ansible\-//')
	git clone --depth=1 git://github.com/debops/${role} /home/travis/build/debops/debops-playbooks/roles/debops.${slug}
done


assert_playbook_runs
assert_playbook_idempotent

