#!/bin/bash

# test: Test debops.tcpwrappers
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/hosts.allow.d"
assert_in_file "/etc/hosts.allow" "127.0.0.0/8"
assert_docs

