#!/bin/bash

# test: Test debops.apt
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"

# Prevent auto-start of unconfigured service
cat <<EOF | sudo tee /usr/sbin/policy-rc.d
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF
sudo chmod +x /usr/sbin/policy-rc.d

install_ansible ${test_ansible_version}
ansible_plugins

assert_playbook_check_runs
assert_playbook_idempotent

assert_path /etc/gdnsd/config
assert_running gdnsd
assert_in "$(dig @127.0.0.1 localdomain SOA)" "ANSWER SECTION"
assert_in "$(dig @127.0.0.1 localdomain NS)" "ANSWER SECTION"
assert_in "$(dig @127.0.0.1 ${HOSTNAME}.localdomain)" "ANSWER SECTION"
addr="$(dig @127.0.0.1 +short ${HOSTNAME}.localdomain)"
assert_in "$(dig @127.0.0.1 -x ${addr})" "ANSWER SECTION"

assert_docs
