#!/bin/bash

# test: Test debops.apt_cacher_ng
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.etc_services
ansible-galaxy -f install debops.apt_preferences
ansible-galaxy -f install debops.ferm

assert_playbook_check_runs
assert_playbook_idempotent


assert_path '/etc/apt-cacher-ng'
assert_path '/var/cache/apt-cacher-ng'
assert_permission /etc/apt-cacher-ng/security.conf '640'

assert_running 'apt-cacher-ng'

assert_url 'http://localhost:3142/' '(200|40[46])'

assert_docs
