#!/bin/bash

# test: Test debops.samba
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# Create missing modules-load.d directory
sudo mkdir -p /etc/modules-load.d


# Try newer packages
echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/wily.list
sudo apt-get -yq update

# Clear out stale files
sudo rm -f /etc/dpkg/dpkg.cfg.d/multiarch


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/samba/smb.conf"
#assert_docs

