#!/bin/bash

# test: Test debops.samba
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# Create missing modules-load.d directory
sudo mkdir -p /etc/modules-load.d


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/samba/smb.conf"
assert_docs

