#!/bin/bash

# test: Test debops.mailman
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki debops.ferm debops.postfix debops.fcgiwrap debops.unattended_upgrades debops.secret debops.apt_preferences debops.nginx


assert_playbook_check_runs
assert_playbook_idempotent


ls -l /etc/nginx/sites-enabled
cat /etc/nginx/sites-enabled/*

cat /etc/pki/realms/domain/internal/gnutls.conf

mailman_host="$(hostname -f)"

echo "Test http with '${mailman_host}'"
curl -v http://${mailman_host}/

echo "Test https"
curl -v https://${mailman_host}/

echo "Test https proper"
curl -v https://${mailman_host}/mailman/listinfo/

assert_path "/var/lib/mailman/lists/mailman/config.pck"
assert_path "/var/lib/mailman/lists/test-list/config.pck"
assert_url "http://${mailman_host}/" 301
assert_url "https://${mailman_host}/mailman/listinfo/"
assert_docs

