#!/bin/bash

# test: Test debops.apt_preferences
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


assert_playbook_runs
assert_playbook_idempotent

# Check list of configured apt preferences
cat /etc/apt/preferences.d/*

# Check APT policy for nginx package
apt-cache policy nginx

