#!/bin/bash

# test: Test debops.sshd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


assert_in_file "/etc/ssh/sshd_config" "PermitRootLogin without-password"
assert_in_file "/etc/ssh/sshd_config" "PasswordAuthentication no"

assert_docs

