#!/bin/bash

# test: Test debops.cryptsetup
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

# Can not be tested as loop devices are not supported on Travis.
# https://github.com/travis-ci/travis-ci/issues/1119
for i in $(seq 0 4)
do
	echo "Creating loop${i}"
	truncate --size=42M "/tmp/ciphertext_loop${i}_file.raw"
	# sudo losetup "$(losetup --find)" "/tmp/ciphertext_loop${i}_file.raw"
done

assert_playbook_check_runs
assert_playbook_idempotent


assert_docs
