#!/bin/bash

# test: Test debops.ansible
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


# At the moment on Ubuntu Precise available on Travis CI, python-crypto package
# is too old for ansible package (unmet version dependencies). Let's add a newer
# version before the playbook is tested
if [ -n "${ROLESPEC_TRAVIS}" ] ; then
  dist="saucy"
  echo "Upgrade python-crypto to >= 2.6 for Ansible"
  echo "deb http://us.archive.ubuntu.com/ubuntu/ ${dist} main restricted" | sudo tee /etc/apt/sources.list.d/${dist}.list
  sudo apt-get -qq update
  sudo apt-get -yq install python-crypto/${dist}
fi


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(ansible --version)" "ansible"
