#!/bin/bash

# test: Test debops.etherpad
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


# Fix missing insserv command in Ubuntu Precise
if [ -n "${ROLESPEC_TRAVIS}" ] ; then
  sudo ln -s /usr/lib/insserv/insserv /usr/sbin/insserv
fi


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}


ansible-galaxy install -f debops.pki


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}


assert_playbook_runs
assert_playbook_idempotent


assert_url "https://${ROLESPEC_FQDN}"
