#!/bin/bash

# test: Test debops.etherpad
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


stop mysql
purge $mysql_libs


assert_playbook_runs
assert_playbook_idempotent


assert_url "https://$fqdn"
