#!/bin/bash

# test: Test debops.lxc
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Try fixing AppArmor to avoid issues on Travis-CI
echo "Fix AppArmor support"
sudo touch /etc/apparmor.d/tunables/global

install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.apt_preferences debops.postfix
ansible-galaxy -f install debops.ferm debops-contrib.apparmor

# Add Ubuntu Trusty repository
if [ -n "${ROLESPEC_TRAVIS}" ] ; then
    echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/trusty.list
    sudo apt-get -qq update
    sudo apt-get -y install ubuntu-keyring
    sudo apt-get -qq update
fi


echo "Check if lxc is installed"
dpkg -l | grep lxc


assert_playbook_check_runs

echo "Check package policies"
apt-cache policy lxc lxc-templates


assert_playbook_idempotent


assert_path "/etc/lxc/lxc.conf"
assert_path "/var/lib/lxc"
