#!/bin/bash

# test: Test debops.lxc
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Add Ubuntu Trusty repository
if [ -n "${ROLESPEC_TRAVIS}" ] ; then
    echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/trusty.list
    sudo apt-get -qq update
fi


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/lxc/lxc.conf"
assert_path "/var/lib/lxc"

