#!/bin/bash

# test: Test debops.debops
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


sleep 10
ls -lR /usr/local/share


assert_path "/usr/local/bin/debops"
assert_path "/usr/local/share/debops/debops-playbooks/playbooks/site.yml"

