---

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx__dependent_maps:
        - '{{ homeassistant__nginx__dependent_maps }}'
      nginx__dependent_upstreams:
        - '{{ homeassistant__nginx__dependent_upstreams }}'
      nginx__dependent_servers:
        - '{{ homeassistant__nginx__dependent_servers }}'

    - role: 'ansible-homeassistant'
