#!/bin/bash

# test: Test debops.gitlab
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Add Ruby 2.1 PPA
sudo apt-get -yq install python-software-properties
sudo apt-add-repository -y ppa:brightbox/ruby-ng
sudo apt-get -yq update
sudo apt-get -yq install ruby2.1 ruby2.1-dev


#install_ansible ${test_ansible_version}
install_ansible v1.8.2
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


# GitLab needs some time to start up
sleep 15


# Check page content
curl http://localhost.localdomain

assert_url "http://localhost.localdomain/"

