#!/bin/bash

# test: Test debops.gitlab
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


# Add Ruby 2.1 PPA
sudo apt-get install python-software-properties
sudo apt-add-repository -y ppa:brightbox/ruby-ng
sudo apt-get -yq update

#install_ansible ${test_ansible_version}
install_ansible v1.8.2
ansible_plugins


ansible-galaxy install -f debops.pki debops.apt debops.auth


assert_playbook_runs
assert_playbook_idempotent


assert_url "https://localhost.localdomain/"

