---

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    ## Run role from the `common.yml` playbook.
    ## debops.apt: To ensure that backports in Ubuntu are enabled.
    - role: 'debops.apt'

    ## Run required (for default debops.owncloud configuration) role before the main owncloud.yml playbook.
    - role: 'debops.mariadb_server'
    ## Run optional role before the main owncloud.yml playbook.
    - role: 'debops.redis'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'
        - '{{ owncloud__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.mariadb
      tags: [ 'role::mariadb' ]
      mariadb_users:
        - database: '{{ owncloud__database_map[owncloud__database].dbname }}'
          user: '{{ owncloud__database_map[owncloud__database].dbuser }}'
          password: '{{ owncloud__database_map[owncloud__database].dbpass }}'
      when: (owncloud__database == 'mariadb')

    - role: debops.php5
      tags: [ 'role::php5' ]
      php5_pools:
        - '{{ owncloud__php5__pool }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_dependent_servers:
        - '{{ owncloud__nginx__servers }}'
      nginx_dependent_upstreams:
        - '{{ owncloud__nginx__upstream_php5 }}'

    - role: 'ansible-owncloud'

