#!/bin/bash

# test: Test debops.bootstrap
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

# Suddently /etc/hosts on Travis has no newline character at the end, which breaks the idempotency. Let's try to fix it.
if [ -s "/etc/hosts" ] && [ "$(tail -c1 "/etc/hosts"; echo x)" != $'\nx' ]; then
    echo "" | sudo tee -a "/etc/hosts"
fi

cp /etc/hosts ~/hosts

assert_playbook_check_runs --diff

echo "======================================"
diff /etc/hosts ~/hosts
echo "======================================"

assert_playbook_idempotent --diff


assert_docs

