#!/bin/bash

# test: Test debops.rsyslog
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.logrotate debops.etc_services debops.apt_preferences debops.ferm


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/rsyslog.d"
assert_path "/etc/rsyslog.d/00-global.conf"
assert_running "rsyslogd"
assert_docs

