#!/bin/bash

# test: Test debops.golang
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(go version)" "go"
