#!/bin/bash

# test: Test debops.checkmk_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.apt_preferences
ansible-galaxy -f install debops.authorized_keys
ansible-galaxy -f install debops.etc_services
ansible-galaxy -f install debops.ferm
ansible-galaxy -f install debops.tcpwrappers
ansible-galaxy -f install debops.mariadb

assert_playbook_check_runs
assert_playbook_idempotent


assert_path '/etc/check_mk'
assert_path '/usr/bin/check_mk_agent'

assert_group 'checkmk'
assert_exit_code 'getent passwd checkmk' 0

assert_path '/etc/ssh/authorized_keys/checkmk'
assert_path '/etc/sudoers.d/check-mk-agent'


assert_docs
