#!/bin/bash

# test: Test debops.pki
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


#install_ansible ${test_ansible_version}
install_ansible devel 01d3dc2e9dbfb679c084a515378b96b187b1ed1c
ansible_plugins


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/pki/host"
assert_path "/etc/pki/domain"

assert_in_file "/etc/pki/system/default.crt" "CERTIFICATE"
assert_in_file "/etc/pki/system/default.key" "PRIVATE KEY"
