#!/bin/bash

# test: Test debops.tinc
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.secret
ansible-galaxy -f install debops.apt_preferences
ansible-galaxy -f install debops.etc_services
ansible-galaxy -f install debops.ferm


assert_playbook_check_runs
echo "------------------------------------------------------------"
ls -lR /etc/tinc
echo "------------------------------------------------------------"
cat /etc/tinc/mesh0/tinc.conf
echo "------------------------------------------------------------"
cat /etc/tinc/mesh0/hosts/*
echo "------------------------------------------------------------"
assert_playbook_idempotent


assert_path "/etc/tinc/mesh0/tinc.conf"

assert_docs
