#!/bin/bash

# test: Test debops.tinc
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.subnetwork


assert_playbook_runs
assert_playbook_idempotent


assert_path "/etc/tinc/mesh0/tinc.conf"
assert_running "tincd"

assert_docs

