#!/bin/bash

# test: Test debops.phpiam
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.mysql


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}


assert_playbook_runs
assert_playbook_idempotent


assert_url "http://${ROLESPEC_FQDN}/?page=login"
