#!/bin/bash

# test: Test debops.phpiam
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}


assert_playbook_runs
assert_playbook_idempotent


assert_url "https://${ROLESPEC_FQDN}"
