#!/bin/bash

# test: Test debops.console
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


assert_playbook_runs
assert_playbook_idempotent


assert_in_file "/etc/motd" "managed by Ansible"
assert_in_file "/etc/issue" "Organization"
assert_in "$(echo "${LANG}")" "en_US.UTF-8"
