#!/bin/bash

# test: Test debops.console
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ls -l /etc/motd
assert_playbook_runs
ls -l /etc/motd
assert_playbook_idempotent
ls -l /etc/motd


assert_in_file "/etc/motd" "managed by Ansible"
assert_in_file "/etc/issue" "Organization"
assert_in "$(echo "${LANG}")" "en_US.UTF-8"
