#!/bin/bash

# test: Test debops.slapd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki


assert_playbook_check_runs
assert_playbook_idempotent


assert_group stunnel4
assert_running "stunnel4"
assert_path "/etc/stunnel/test-service.conf"

# Test documentation
assert_docs

