#!/bin/bash

# test: Test debops.core
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
echo "/etc/ansible/facts.d/root.fact"
cat /etc/ansible/facts.d/root.fact
assert_playbook_idempotent || true
echo "/etc/ansible/facts.d/root.fact"
cat /etc/ansible/facts.d/root.fact
assert_ansible_check_diff


assert_path "/etc/ansible/facts.d"
assert_path "/etc/ansible/facts.d/core.fact"
assert_docs

