#!/bin/bash

# test: Test debops.apt_install
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences


assert_playbook_check_runs
assert_playbook_idempotent


# Check if vim is installed by Ansible
assert_in "$(vim --version)" "VIM"

assert_docs
