#!/bin/bash

# test: Test debops.atd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/at.allow"
assert_path "/etc/at.deny"
assert_in_file "/etc/at.allow" "${USER}"
assert_running "atd"
assert_docs

