#!/bin/bash

# test: Test debops.java
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


purge openjdk-6-jre openjdk-7-jre default-jre default-jre-headless


assert_playbook_runs
assert_playbook_idempotent


assert_in "$(java -version 2>&1)" "1.7"
