#!/bin/bash

# test: Test debops.swapfile
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# Fake the swapfile becaue Travis-CI lies about 'cap_sys_admin' being available
# and swapfile cannot be enabled. Thus, test basically checks Ansible playbook
# syntax.
sudo touch /swapfile


assert_playbook_check_runs
assert_playbook_idempotent


assert_docs

