#!/bin/bash

# test: Test debops.postgresql
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.postgresql_server


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}
sudo rm -rf /var/lib/postgresql


assert_playbook_check_runs
assert_playbook_idempotent


psql -d travis_test -c '\l'
psql -d travis_test -c '\du'


assert_running "postgres"
assert_in_file "/home/travis/.pgpass" "travis"
assert_in "psql -d travis_test -c '\l'" "travis_test"
assert_in "psql -d travis_test -c '\du'" "travis_test"
assert_docs

