#!/bin/bash

# test: Test debops.postgresql
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"


install_ansible


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}


assert_playbook_runs
assert_playbook_idempotent


assert_running "postgres"
assert_in_file "/etc/postgresql/9.1/main/pg_hba.conf" "192.168.0.0/16"
assert_in_file "/etc/postgresql/9.1/main/postgresql.conf" "0.0.0.0"
assert_iptables_allow "postgresql"
