#!/bin/bash

# test: Test debops.etc_services
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "lib/test"


assert_playbook_runs
assert_playbook_idempotent

# Check if existing services are available
assert_in_file "/etc/services" "80/tcp"

# Check if our custom service is added
assert_in_file "/etc/services" "testservice"

